name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main # Change to your default branch name

jobs:
  generate:
    permissions:
      contents: write
      pull: read
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: yassersalem74 # Replace with your GitHub username
          outputs: output/snake.svg?palette=github-dark # Ensure the directory exists

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # Ensure this branch exists
          build_dir: output # Match the directory used in the previous step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
